services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=supply_chain_local
      - MYSQL_USER=supply_chain
      - MYSQL_PASSWORD=password

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  hashicorp:
    image: hashicorp/vault:1.21
    container_name: hashicorp
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=root
    ports:
      - "8200:8200"
    restart: unless-stopped
    command:
      sh -c "vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200 &
      sleep 5 &&
      VAULT_ADDR=http://127.0.0.1:8200 VAULT_TOKEN=root vault secrets enable transit &&
      wait"
    volumes:
      - hashicorp_vault_data:/vault/file

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server
      IPFS_PATH: /data/ipfs
    ports:
      # Swarm
      - "4001:4001/tcp"
      - "4001:4001/udp"
      # API
      - "5001:5001"
      # Gateway
      - "8080:8080"
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export

  redis:
    image: redis:latest
    container_name: redis-gas-station
    volumes:
      - redis_data:/data

  gas-station:
    image: iotaledger/gas-station:0.3.1
    container_name: gas-station-iota
    command: ["--config-path", "/app/config.yaml"]
    depends_on:
      - redis
    ports:
      - "9527:9527" # RPC port
      - "9184:9184" # Metrics port
    environment:
      - CONFIG_PATH=/app/config.yaml
      - RUST_BACKTRACE=1
      - GAS_STATION_AUTH=token
    volumes:
      - ${LOCAL_CONFIG_PATH:-./config.yaml}:/app/config.yaml

  localstack:
    container_name: localstack-main
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - localstack_data:/var/lib/localstack

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/fullchain.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./certs/privkey.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - hashicorp

volumes:
  hashicorp_vault_data:
  redis_data:
  mysql_data:
  ipfs_data:
  ipfs_staging:
  localstack_data:
