---
signer-config:
  local:
    keypair: AI2u9nppR0KmbmovuD4nSJBtifoN5YYkdWOUykhJyTSt
rpc-host-ip: 0.0.0.0
rpc-port: 9527
metrics-port: 9184
storage-config:
  redis:
    redis_url: "redis://redis:6379"
# If you change this, you need to flush the Redis database
fullnode-url: "https://api.testnet.iota.cafe"
coin-init-config:
  # If you change this, you need to flush the Redis database
  target-init-balance: 100000000
  refresh-interval-sec: 86400
daily-gas-usage-cap: 1500000000000
access-controller:
  access-policy: disabled