events {}
http {
    map $host $tenant_api_key {
        default                     "";
        api.supply-chain.localhost "d14705dd1afa890054f41fb354113574";
    }

    # HTTP -> HTTPS redirect
    server {
        listen 80;

        server_name app.supply-chain.localhost api.supply-chain.localhost;

        return 301 https://$host$request_uri;
    }

    # Backend
    server {
        listen 443 ssl;
        http2 on;
        server_name api.supply-chain.localhost;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        # Optional hardening (enable once you’re sure HTTPS is correct)
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location / {
            if ($tenant_api_key = "") {
                return 401 '{"error": {"source": "nginx proxy server", "message": "tenant api key not set. try a different hostname"}}';
            }

            # Inject API key into request headers
            proxy_set_header x-api-key $tenant_api_key;

            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://host.docker.internal:3000;
        }
    }

    # Frontend
    server {
        listen 443 ssl;
        http2 on;
        server_name app.supply-chain.localhost;

        ssl_certificate     /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        # Optional hardening (enable once you’re sure HTTPS is correct)
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        location / {
            proxy_pass http://host.docker.internal:4200;
        }
    }
}